//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daycare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickups
    {
        public int pickup_id { get; set; }
        public Nullable<int> daycare_id { get; set; }
        public Nullable<System.DateTime> pickup_date { get; set; }
        public Nullable<long> pickup_charge { get; set; }
    
        public virtual Daycares Daycares { get; set; }
    }
}
